### ISSUE TITLE
Issue with giving a password to mysql

### ISSUE THREAD

**Issue by amolc** [pm2-hive/pm2-mysql#5] opened 2015-12-06 12:11 UTC
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Handshake.ErrorPacket (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
    at Protocol._parsePacket (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    --------------------
    at Protocol._enqueue (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/Connection.js:123:18)
    at Query._callback (/root/.pm2/node_modules/pm2-mysql/lib/queries.js:77:15)
    at Query.Sequence.end (/root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at /root/.pm2/node_modules/pm2-mysql/node_modules/mysql/lib/protocol/Protocol.js:220:14
    at process._tickDomainCallback (node.js:486:13)

**Comment by alavit-d** [comment] 2015-12-09 14:21
Hi, did you give the Mysql password to the pm2-mysql module? To check go to `~/.pm2/module_conf.json`, you should have something like

``` json
"pm2-mysql": {
        "password": "yourpass"
    }
```

You can then edit directly this file or use `pm2 set pm2-mysql:password yourpass`

**Comment by Matungos** [comment] 2016-04-07 21:34
The problem is the password web setup fails.
The request returns:
TypeError: Cannot read property 'server_name' of undefined

**Comment by alavit-d** [comment] 2016-12-12 18:41
Should be fixed with https://github.com/pm2-hive/pm2-mysql/commit/4a741033722b6a430707a5d1ce432bb7e9fcc53a and module refactor, please reopen if you still experience those issues

**Closed as completed by alavit-d** 2016-12-12 18:41 UTC
